// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7b8_bMbzFlNX7sqNylotlZ_jzzumlByY',
    appId: '1:788770189156:web:ce2aa41a06daf4f1a5d471',
    messagingSenderId: '788770189156',
    projectId: 'money-manager-47c19',
    authDomain: 'money-manager-47c19.firebaseapp.com',
    storageBucket: 'money-manager-47c19.appspot.com',
    measurementId: 'G-DNL0ELQP90',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOO_JbT-JKzKz13ay5BKSw0dPvGrQRJ-Q',
    appId: '1:788770189156:android:d0e05cec2f8c9afba5d471',
    messagingSenderId: '788770189156',
    projectId: 'money-manager-47c19',
    storageBucket: 'money-manager-47c19.appspot.com',
  );
}
